Added: Separate trigger/routines dump

diff --git a/mysql-mariadb-snapshot b/mysql-mariadb-snapshot
--- a/mysql-mariadb-snapshot
+++ b/mysql-mariadb-snapshot
@@ -94,17 +94,27 @@ for DB in $DB_LIST; do
     # check success
     if [ $? -ne 0 ]; then
         echo " |- ERROR: mysqldump of $DB DATA failed!"
-        RETURN_CODE=10
+        RETURN_CODE=20
         continue
     fi
 
     # dump db STRUCTURE (including views)
-    $MYSQLDUMP_BIN --defaults-extra-file=$MYSQL_CONF --socket=$MYSQL_SOCKET $MYSQLDUMP_OPT --no-data --triggers --routines --create-options $DB > $MYSQL_TMP_DIR/$NOW/$DB.structure.sql
+    $MYSQLDUMP_BIN --defaults-extra-file=$MYSQL_CONF --socket=$MYSQL_SOCKET $MYSQLDUMP_OPT --no-data --create-options --skip-triggers $DB > $MYSQL_TMP_DIR/$NOW/$DB.structure.sql
 
     # check success
     if [ $? -ne 0 ]; then
         echo " |- ERROR: mysqldump of $DB STRUCTURE failed!"
-        RETURN_CODE=11
+        RETURN_CODE=21
+        continue
+    fi
+
+    # dump db PROCEDURES + TRIGGERS
+    $MYSQLDUMP_BIN --defaults-extra-file=$MYSQL_CONF --socket=$MYSQL_SOCKET $MYSQLDUMP_OPT --triggers --routines --no-data --no-create-info $DB > $MYSQL_TMP_DIR/$NOW/$DB.procedures.sql
+
+    # check success
+    if [ $? -ne 0 ]; then
+        echo " |- ERROR: mysqldump of $DB PROCEDURES/TRIGGERS failed!"
+        RETURN_CODE=22
         continue
     fi
 done
